name: pisjo
description: "Aplikasi untuk produk Pisang Ijo Mameen Samarinda"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  flutter_launcher_icons: ^0.13.1
  intl: ^0.19.0

flutter_launcher_icons:
  image_path: "images/logo.png"
  android: true
  ios: true
  web:
    generate: true
    image_path: "images/logo.png"


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - images/
